# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='monedes_pendents',
            field=models.IntegerField(default=5),
        ),
    ]
