# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_perfil_monedes_pendents'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ultima_peticio',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 13, 4, 8, 779773, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='monedes_pendents',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
    ]
