# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0005_auto_20160530_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imatge',
            field=models.ImageField(default='/usuaris_imatges/defaultUser.png', max_length=500, upload_to='usuaris_imatges'),
        ),
    ]
