# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0006_perfil_imatge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='monedes_pendents',
            field=models.DecimalField(decimal_places=4, default=50, max_digits=10),
        ),
    ]
