# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_element_usuaris_que_tenen_aquest_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='peix',
            name='atac',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peix',
            name='velocitat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peix',
            name='vida',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
